INSERT INTO departments (department_name)
VALUES
    ('Executive'),
    ('Marketing'),
    ('Info Tech'),
    ('Finance'),
    ('Operations'),
    ('Administration'),
    ('Human Resources'),
    ('Public Relations');

INSERT INTO roles (job_title, salary, dept_id, is_management)
VALUES
    ('President', 70000, 1, true),
    ('Vice President', 60000, 1, true),
    ('Marketing Manager', 50000, 2, true),
    ('IT Manager', 55000, 3, true),
    ('Finance Manager', 50000, 4, true),
    ('Operations Manager', 50000, 5, true),
    ('Admin Assistant', 35000, 6, false),
    ('HR Rep', 35000, 7, false),
    ('PR Rep', 35000, 8, false),
    ('Marketing Rep', 35000, 2, false),
    ('Developer', 40000, 3, false),
    ('Accountant', 35000, 4, false),
    ('Data Clerk', 31000, 5, false),
    ('Customer Service', 31000, 5, false),
    ('Operations Attendant', 31000, 5, false);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES
    ('Steven', 'King', 1, 1),
    ('Lex', 'De Haan', 2, 1),
    ('Neena', 'Kochhar', 2, 1),
    ('Michael', 'Hartstein', 3, 1),
    ('Alexander', 'Hunold', 4, 2),
    ('Nancy', 'Greenberg', 5, 3),
    ('Matthew', 'Weiss', 6, 1),
    ('Adam', 'Fripp', 6, 1 ),
    ('Payam', 'Kaufling', 6, 1),
    ('Shanta', 'Vollman', 6, 1),
    ('Jennifer', 'Whalen', 7, 3),
    ('Susan', 'Mavris', 8, 3),
    ('Hermann', 'Baer', 9, 3),
    ('Pat', 'Fay', 10, 4),
    ('Bruce', 'Ernst', 11, 5),
    ('David', 'Austin', 11, 5),
    ('Valli', 'Pataballa', 11, 5),
    ('Diana', 'Lorentz', 11, 5),
    ('Daniel', 'Faviet', 12, 6),
    ('John', 'Chen', 12, 6),
    ('Ismael', 'Sciarra', 12, 6),
    ('Jose Manuel', 'Urman', 12, 6),
    ('Luis', 'Popp', 12, 6),
    ('Julia', 'Nayer', 13, 7),
    ('Irene', 'Mikkilineni', 13, 7),
    ('James', 'Landry', 13, 7),
    ('Steven', 'Markle', 13, 7),
    ('Laura', 'Bissot', 14, 8),
    ('Mozhe', 'Atkinson', 14, 8),
    ('James', 'Marlow', 14, 8),
    ('TJ', 'Olson', 14, 8),
    ('Jason', 'Mallin', 15, 9),
    ('Michael', 'Rogers', 15, 9),
    ('Ki', 'Gee', 15, 9),
    ('Hazel', 'Philtanker', 15, 9),
    ('Renske', 'Ladwig', 15, 10),
    ('Stephen', 'Stiles', 15, 10),
    ('John', 'Seo', 15, 10),
    ('Joshua', 'Patel', 15, 10);
